##
## Copyright (c) 2022 Salesforce.com, inc.
## All rights reserved.
## SPDX-License-Identifier: BSD-3-Clause
## For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
##
##

# YAML file for log BERT on BGL Anomaly Detection 

data_loader_config:
  filepath: "../../datasets/public/Thunderbird/Thunderbird.log"
  log_type: 'csv'
  dimensions:
    attributes: ['timestamp', 'Label']
    body: ['Content']
  header: 0