##
## Copyright (c) 2022 Salesforce.com, inc.
## All rights reserved.
## SPDX-License-Identifier: BSD-3-Clause
## For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
##
##

# YAML file for log BERT on HDFS Anomaly Detection 

data_loader_config:
  filepath: "/Users/qcheng/workspace/gitsoma/logai/logai/data/open_datasets/HDFS_1/HDFS.log"
  label_filepath: "/Users/qcheng/workspace/gitsoma/logai/logai/data/open_datasets/HDFS_1/anomaly_label.csv"
  log_type: 'csv'
  dimensions:
    attributes: ['timestamp']
    body: ['Content']
  header: 0
